FROM ubuntu

WORKDIR /home/ssl

RUN apt-get -y update && \
    apt -y install --no-install-recommends build-essential && \
    apt -y install --no-install-recommends flex && \
    apt -y install --no-install-recommends bison && \
    rm -rf /var/lib/apt/lists/*