/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_acclist[338] =
    {   0,
       71,   69,   70,   67,   69,   70,   68,   70,   67,   69,
       70,   57,   69,   70,   69,   70,   69,   70,   57,   69,
       70,   57,   69,   70,   69,   70,   57,   69,   70,   57,
       69,   70,   57,   69,   70,   57,   69,   70,   63,   69,
       70,   57,   69,   70,   60,   69,   70,   62,   69,   70,
       57,   69,   70,   57,   69,   70,   57,   69,   70,   58,
       69,   70,   57,   69,   70,   58,   69,   70,   58,   69,
       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       58,   69,   70,   58,   69,   70,   58,   69,   70,   58,
       69,   70,   58,   69,   70,   58,   69,   70,   58,   69,

       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       57,   69,   70,   67,   68,   67,   39,   59,   51,   36,
       54,   47,   44,   63,   49,   45,   50,   46,   63,   65,
       48,   63,   60,   62,   43,   40,   38,   41,   42,   58,
       55,   58,   58,   58,   58,   58,   58,   26,   58,   58,
       58,   58,   58,   58,   58,   22,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   56,   35,
       64,   37,   63,   65,   63,   61,   53,   52,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   25,
       58,   58,   11,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   66,
       63,    3,   58,   58,   20,   58,    9,   58,   58,   58,
       58,   58,   24,   58,   19,   58,   58,   58,   28,   58,
       12,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,    8,   58,   58,   58,   30,   58,   17,
       58,   58,   58,   58,   58,   13,   58,   58,   58,   10,
       58,   58,   58,   58,   58,   58,   58,   32,   58,   58,
       58,   27,   58,   58,   58,   14,   58,    6,   58,   58,
       33,   58,   15,   58,   34,   58,    5,   58,   31,   58,
       23,   58,   58,   58,   58,   58,   21,   58,   58,    7,

       58,   58,   58,   29,   58,    4,   58,   16,   58,   18,
       58,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_accept[302] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       19,   22,   25,   27,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   57,   60,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   99,  102,  105,
      108,  111,  114,  115,  116,  117,  118,  118,  119,  119,
      119,  119,  120,  121,  122,  122,  122,  122,  122,  122,
      122,  123,  124,  125,  125,  126,  127,  128,  129,  129,
      130,  130,  130,  131,  132,  133,  134,  134,  134,  134,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
      145,  146,  147,  148,  150,  151,  152,  153,  154,  155,

      156,  158,  159,  160,  161,  162,  163,  164,  165,  166,
      167,  168,  169,  170,  171,  171,  171,  171,  172,  173,
      173,  174,  174,  174,  175,  175,  175,  176,  177,  178,
      179,  180,  181,  182,  183,  184,  185,  186,  187,  188,
      189,  190,  192,  193,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      210,  210,  211,  211,  212,  214,  215,  217,  219,  220,
      221,  222,  223,  225,  227,  228,  229,  231,  233,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,
      246,  247,  248,  248,  248,  250,  252,  253,  254,  255,

      256,  258,  259,  260,  262,  263,  264,  265,  266,  267,
      268,  270,  271,  272,  274,  274,  274,  275,  276,  278,
      280,  281,  283,  285,  287,  289,  291,  293,  294,  295,
      296,  296,  296,  297,  299,  300,  302,  303,  304,  304,
      304,  306,  308,  310,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  313,  314,  315,  315,  316,  316,  316,
      316,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      318,  318,  319,  320,  320,  320,  321,  322,  322,  323,
      324,  325,  326,  326,  326,  327,  327,  327,  328,  329,
      330,  331,  332,  333,  333,  334,  335,  336,  337,  338,

      338
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   30,   30,   32,   31,
       33,   34,   34,   33,   33,   35,   34,   34,   34,   34,
       33,   33,   34,   34,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   34,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   70,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   71,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    2,    3,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[311] =
    {   0,
        0,    0,  693,  694,  690,  688,  685,  662,   65,   28,
      661,   63,  100,  694,  660,   60,   70,  151,   80,  156,
      163,   58,  659,   74,    0,  658,  624,  626,  145,   31,
      138,   44,  627,   75,  626,  634,  149,  615,  624,  622,
      627,  113,  673,  671,  668,  694,   73,  694,  669,  625,
      616,  694,  694,  694,  184,  657,  656,  655,  654,  595,
      694,  694,  182,  194,  694,  694,  694,  694,  645,  199,
      211,  648,    0,  694,  214,  220,  232,  240,    0,  248,
      635,  694,  694,  694,  634,    0,  694,  601,  613,  600,
      615,  602,  608,  594,  595,  592,  592,  595,  592,  589,

        0,  588,  592,  159,  590,   73,  134,  594,  587,  180,
       89,  592,  694,  694,  594,  596,  245,  694,  694,  202,
      226,  624,  253,    0,  261,  253,  264,    0,  694,  694,
      583,  595,  590,  578,  230,  592,  590,  586,  578,  584,
      587,    0,  573,    0,  579,  576,  565,  567,  569,  576,
      562,  560,  560,  572,  562,  566,  570,  572,  561,  562,
      559,  694,  269,  274,    0,  559,    0,    0,  550,  558,
      547,  554,    0,    0,  537,  524,    0,    0,  517,  499,
      496,  508,  498,  498,  503,  498,  493,  483,  487,    0,
      472,  484,  474,  467,    0,    0,  468,  465,  459,  450,

        0,  443,  429,    0,  432,  424,  426,  407,  411,  413,
        0,  400,  399,    0,  401,  398,  382,  381,    0,    0,
      388,    0,    0,    0,    0,    0,    0,  386,  383,  345,
      296,  333,  331,    0,  297,    0,  305,  299,  300,  304,
        0,    0,    0,    0,  308,  312,  337,  205,    0,  286,
      356,  299,  305,  409,  416,  324,  694,  278,  231,  329,
      694,  207,  260,  194,  169,  111,   91,   24,  311,  435,
      457,  442,  463,  468,  485,  287,  294,    0,  497,  288,
      300,   47,  373,  373,  471,  518,  489,  503,  694,  694,
      461,  694,  694,  523,  529,  390,  401,  694,  694,  694,

      557,  560,  566,  572,  575,  579,  585,  591,  597,  600
    } ;

static yyconst short int yy_def[311] =
    {   0,
      300,    1,  300,  300,  300,  300,  300,  300,  301,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  302,  300,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  300,  300,  300,  300,  300,  301,  300,  301,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  303,  304,  300,  300,  300,  300,  300,  305,  300,
      300,  300,  300,  300,  300,  302,  300,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  303,  303,  304,  300,  300,  300,  305,  300,  300,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  300,
      300,  300,  300,  300,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  300,  300,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  300,  300,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      300,  300,  302,  302,  302,  302,  302,  302,  306,  300,
      302,  302,  302,  302,  306,  300,  300,  307,  308,  309,
      300,  300,  300,  300,  300,  307,  300,  307,  308,  309,
      300,  309,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  310,  300,  300,
      300,  308,  300,  300,  300,  300,  300,  300,  300,  300,
      310,  300,  300,  300,  300,  300,  300,  300,  300,    0,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst short int yy_nxt[766] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,    4,   11,
       12,   13,   14,   14,   15,   16,   14,   17,   18,   19,
       20,   21,   21,   14,   14,   22,   23,   24,   14,   25,
       25,   25,   25,   25,   25,   25,   25,   14,    4,   14,
       26,   27,   28,   29,   30,   31,   32,   33,   25,   34,
       25,   35,   25,   25,   25,   25,   36,   37,   38,   39,
       40,   41,   25,   25,   25,   14,   42,   14,   14,    4,
        4,   48,   50,   53,  282,   62,   93,   51,   63,   48,
       64,   64,   64,   81,   82,   94,   65,   66,   63,   54,
       64,   64,   64,  264,   72,   98,   67,   68,   99,   73,

       84,   85,  261,   49,   55,   56,   74,   56,   56,   56,
       56,   49,   56,   56,   56,   56,   56,   56,   56,   56,
      149,  101,  261,   56,   56,   56,   56,   56,  102,   57,
       58,   57,   58,   57,   57,   57,   57,  150,  157,  113,
      158,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   59,   56,   59,   56,   69,
       60,   70,   70,   70,   75,  151,   76,   76,   77,  114,
      261,   75,   71,   80,   80,   80,   90,   78,  117,   95,
      152,   96,   79,   91,   78,  118,   71,  105,  106,   92,

       97,   78,   70,   70,   70,  261,  146,  107,   78,  300,
      108,  257,   75,   71,   77,   77,   77,  147,   79,   70,
       70,   70,  121,  121,  121,   78,  120,   71,  120,  155,
       71,  121,  121,  121,   70,   70,   70,  156,   75,   78,
       76,   76,   77,  258,   71,  125,  121,  121,  121,  117,
       75,   78,   77,   77,   77,  126,  118,  126,  282,  125,
      127,  127,  127,   78,  283,   78,   75,  123,   80,   80,
       80,  261,  162,  127,  127,  127,  163,   78,  163,   78,
      300,  164,  164,  164,  127,  127,  127,  169,  170,  164,
      164,  164,  261,   78,  164,  164,  164,  239,  239,  239,

      239,  239,  239,  239,  239,  246,  246,  246,  246,  247,
      247,  247,  247,  246,  246,  246,  246,  253,  248,  269,
      269,  269,  289,  292,  262,  270,  270,  270,  290,  272,
      257,  274,  274,  274,  293,  261,  271,  249,  247,  247,
      247,  247,  275,  250,  244,  290,  289,  292,  251,  243,
      271,  293,  252,  242,  252,  253,  275,  254,  255,  255,
      263,  264,  258,  264,  264,  264,  264,  262,  264,  264,
      264,  264,  264,  264,  264,  264,  241,  283,  240,  264,
      264,  264,  264,  264,  261,  265,  266,  265,  266,  265,
      265,  265,  265,  285,  285,  285,  238,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  267,  264,  267,  264,  298,  268,  272,  237,  273,
      273,  274,  236,  235,  272,  299,  279,  279,  279,  234,
      275,  233,  232,  276,  277,  278,  231,  275,  230,  298,
      280,  281,  299,  229,  275,  270,  270,  270,  228,  227,
      276,  275,  270,  270,  270,  226,  271,  280,  277,  225,
      224,  278,  284,  286,  284,  281,  223,  285,  285,  285,
      271,  272,  222,  273,  273,  274,  272,  286,  274,  274,
      274,  285,  285,  285,  275,  296,  297,  276,  277,  275,

      287,  221,  287,  220,  219,  288,  288,  288,  275,  288,
      288,  288,  296,  275,  276,  272,  218,  279,  279,  279,
      297,  217,  277,  288,  288,  288,  216,  215,  275,  214,
      213,  280,  281,  294,  212,  294,  211,  210,  295,  295,
      295,  209,  275,  295,  295,  295,  208,  207,  280,  295,
      295,  295,  206,  205,  204,  203,  281,   47,   47,   47,
       47,   47,   47,   86,   86,   86,  122,  122,  122,  122,
      122,  122,  124,  124,  202,  124,  124,  124,  128,  128,
      245,  245,  201,  245,  245,  256,  256,  256,  256,  256,
      256,  259,  259,  200,  259,  259,  259,  260,  260,  260,

      260,  260,  260,  291,  291,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  168,  167,  166,  165,  123,  161,
      160,  159,  154,  153,  148,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  123,  119,   56,  118,  118,  118,  118,  116,
      115,  300,   45,   44,   43,  112,  111,  110,  109,  104,
      103,  100,   89,   88,   87,   83,   61,   52,   46,   45,
       44,   43,  300,    3,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300
    } ;

static yyconst short int yy_chk[766] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   10,   12,  282,   16,   30,   10,   16,   47,
       16,   16,   16,   22,   22,   30,   16,   17,   17,   12,
       17,   17,   17,  268,   19,   32,   17,   17,   32,   19,

       24,   24,  267,    9,   13,   13,   19,   13,   13,   13,
       13,   47,   13,   13,   13,   13,   13,   13,   13,   13,
      106,   34,  266,   13,   13,   13,   13,   13,   34,   13,
       13,   13,   13,   13,   13,   13,   13,  106,  111,   42,
      111,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   18,
       13,   18,   18,   18,   20,  107,   20,   20,   20,   42,
      265,   21,   18,   21,   21,   21,   29,   20,   55,   31,
      107,   31,   20,   29,   21,   55,   18,   37,   37,   29,

       31,   20,   63,   63,   63,  264,  104,   37,   21,  262,
       37,  248,   64,   63,   64,   64,   64,  104,   20,   70,
       70,   70,  120,  120,  120,   64,   71,   63,   71,  110,
       70,   71,   71,   71,   75,   75,   75,  110,   76,   64,
       76,   76,   76,  248,   70,   75,  121,  121,  121,  117,
       77,   76,   77,   77,   77,   78,  117,   78,  259,   75,
       78,   78,   78,   77,  263,   76,   80,  123,   80,   80,
       80,  263,  123,  126,  126,  126,  125,   77,  125,   80,
      258,  125,  125,  125,  127,  127,  127,  135,  135,  163,
      163,  163,  250,   80,  164,  164,  164,  231,  231,  231,

      231,  239,  239,  239,  239,  240,  240,  240,  240,  245,
      245,  245,  245,  246,  246,  246,  246,  252,  246,  252,
      252,  252,  276,  280,  250,  253,  253,  253,  277,  269,
      256,  269,  269,  269,  281,  260,  253,  246,  247,  247,
      247,  247,  269,  247,  238,  277,  276,  280,  247,  237,
      253,  281,  247,  235,  247,  247,  269,  247,  247,  247,
      251,  251,  256,  251,  251,  251,  251,  260,  251,  251,
      251,  251,  251,  251,  251,  251,  233,  283,  232,  251,
      251,  251,  251,  251,  283,  251,  251,  251,  251,  251,
      251,  251,  251,  284,  284,  284,  230,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  296,  251,  254,  229,  254,
      254,  254,  228,  221,  255,  297,  255,  255,  255,  218,
      254,  217,  216,  254,  254,  254,  215,  255,  213,  296,
      255,  255,  297,  212,  254,  270,  270,  270,  210,  209,
      254,  255,  272,  272,  272,  208,  270,  255,  254,  207,
      206,  254,  271,  272,  271,  255,  205,  271,  271,  271,
      270,  273,  203,  273,  273,  273,  274,  272,  274,  274,
      274,  285,  285,  285,  273,  291,  291,  273,  273,  274,

      275,  202,  275,  200,  199,  275,  275,  275,  273,  287,
      287,  287,  291,  274,  273,  279,  198,  279,  279,  279,
      291,  197,  273,  288,  288,  288,  194,  193,  279,  192,
      191,  279,  279,  286,  189,  286,  188,  187,  286,  286,
      286,  186,  279,  294,  294,  294,  185,  184,  279,  295,
      295,  295,  183,  182,  181,  180,  279,  301,  301,  301,
      301,  301,  301,  302,  302,  302,  303,  303,  303,  303,
      303,  303,  304,  304,  179,  304,  304,  304,  305,  305,
      306,  306,  176,  306,  306,  307,  307,  307,  307,  307,
      307,  308,  308,  175,  308,  308,  308,  309,  309,  309,

      309,  309,  309,  310,  310,  172,  171,  170,  169,  166,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  143,  141,  140,
      139,  138,  137,  136,  134,  133,  132,  131,  122,  116,
      115,  112,  109,  108,  105,  103,  102,  100,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       85,   81,   72,   69,   60,   59,   58,   57,   56,   51,
       50,   49,   45,   44,   43,   41,   40,   39,   38,   36,
       35,   33,   28,   27,   26,   23,   15,   11,    8,    7,
        6,    5,    3,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\flex.l"
#define INITIAL 0
/* %option debug */
#line 6 ".\\flex.l"
#include <stdio.h>
#include <string.h>
#include "bison.tab.h"

int comentario = 0;

/* DEFINICIONES */
/******* DIRECTIVAS PREPROCESAMIENTO *******/
/**************** CONSTANTES ENTERAS *****************/
/******* Constantes Enteras Decimales *******/
/******** Constante Real *********/
/******** Constante Caracter ********/
/****************** LITERAL CADENA *******************/
/******************* IDENTIFICADOR *******************/
/********* Secuencia de Escape **********/
/********* Digitos y Caracteres  ********/
/****************** COMENTARIOS *********************/
/**** OTROS ****/
#line 706 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 ".\\flex.l"

#line 859 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 694 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 69 ".\\flex.l"
{return INCLUDE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 ".\\flex.l"
{return DEFINE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 ".\\flex.l"
{return AUTO;} 	
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 ".\\flex.l"
{return REGISTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 ".\\flex.l"
{return STATIC;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 ".\\flex.l"
{return EXTERN;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 ".\\flex.l"
{return TYPEDEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 ".\\flex.l"
{yylval.cval = yytext; return VOID;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 ".\\flex.l"
{yylval.cval = yytext; return CHAR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 ".\\flex.l"
{return SHORT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 ".\\flex.l"
{yylval.cval = yytext; return INT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 ".\\flex.l"
{return LONG;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 ".\\flex.l"
{yylval.cval = yytext; return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 ".\\flex.l"
{yylval.cval = yytext; return DOUBLE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 ".\\flex.l"
{return SIGNED;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 ".\\flex.l"
{return UNSIGNED;}	
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 ".\\flex.l"
{return CONST;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 ".\\flex.l"
{return VOLATILE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 ".\\flex.l"
{yylval.cval = yytext; return ENUM;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 ".\\flex.l"
{return CASE;}	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 ".\\flex.l"
{return DEFAULT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 ".\\flex.l"
{return IF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 ".\\flex.l"
{return SWITCH;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 ".\\flex.l"
{return ELSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 ".\\flex.l"
{return FOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 ".\\flex.l"
{return DO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 ".\\flex.l"
{return WHILE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 ".\\flex.l"
{return GOTO;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 ".\\flex.l"
{return CONTINUE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 ".\\flex.l"
{return BREAK;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 ".\\flex.l"
{yylval.cval = yytext; return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 ".\\flex.l"
{yylval.cval = yytext; return UNION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 ".\\flex.l"
{return RETURN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 ".\\flex.l"
{return SIZEOF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 ".\\flex.l"
{return CTE_OR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 ".\\flex.l"
{return CTE_AND;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 ".\\flex.l"
{return ELIPSIS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 ".\\flex.l"
{return IGUAL_IGUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 ".\\flex.l"
{return DISTINTO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 108 ".\\flex.l"
{return MENOR_IGUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 ".\\flex.l"
{return MAYOR_IGUAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 110 ".\\flex.l"
{return CORR_DER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 ".\\flex.l"
{return CORR_IZQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 ".\\flex.l"
{return MAS_MAS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 ".\\flex.l"
{return MENOS_MENOS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 ".\\flex.l"
{return FLECHA;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 ".\\flex.l"
{return POR_IGUAL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 116 ".\\flex.l"
{return DIV_IGUAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 ".\\flex.l"
{return MAS_IGUAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 ".\\flex.l"
{return MENOS_IGUAL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 ".\\flex.l"
{return MOD_IGUAL;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 ".\\flex.l"
{return CORR_DER_IGUAL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 ".\\flex.l"
{return CORR_IZQ_IGUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 ".\\flex.l"
{return Y_IGUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 ".\\flex.l"
{return POT_IGUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 ".\\flex.l"
{return O_IGUAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 ".\\flex.l"
{return yytext[0];}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 ".\\flex.l"
{if(comentario == 0) {yylval.cval = yytext; return IDENTIFICADOR;}}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 ".\\flex.l"
{if(comentario == 0) return LITERAL_CADENA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 ".\\flex.l"
{if(comentario == 0) return CONST_OCTAL;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 ".\\flex.l"
{if(comentario == 0) return CONST_HEXADECIMAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 ".\\flex.l"
{if(comentario == 0) return CONST_DECIMAL;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 ".\\flex.l"
{if(comentario == 0) return CONST_PTOFLOTANTE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 ".\\flex.l"
{if(comentario == 0) return CONST_CARACTER;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 ".\\flex.l"
{if(comentario == 0) comentario=1;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 ".\\flex.l"
{if(comentario == 1) comentario = 0; else comentario = 1;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 ".\\flex.l"
{;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 ".\\flex.l"
{comentario=0;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 ".\\flex.l"
{printf("ERROR LEXICO: %s, EN LINEA: %d \n",yytext,yylineno);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 ".\\flex.l"
ECHO;
	YY_BREAK
#line 1300 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 138 ".\\flex.l"


