
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[561] =
    {   0,
       63,   63,   63,   63,   72,   69,   67,   68,   67,   57,
       69,   69,   57,   57,   69,   57,   57,   57,   57,   69,
       57,   60,   62,   57,   57,   57,   58,   57,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   57,   69,   67,   68,   67,   57,   69,
       69,   57,   57,   69,   57,   57,   57,   57,   69,   57,
       60,   62,   57,   57,   57,   58,   57,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   57,   67,   68,   67,   39,    0,   59,    0,
        0,    0,   51,   36,   54,    0,    0,    0,    0,   47,

       44,    0,   63,   49,   45,   50,   46,    0,    0,   63,
        0,   65,   48,    0,   60,   63,   63,    0,   62,   43,
       40,   38,   41,   42,   58,   55,   58,   58,   58,   58,
       58,   58,   26,   58,   58,   58,   58,   58,   58,   22,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   56,   35,    0,   70,   67,   67,   39,    0,   70,
       59,    0,    0,    0,   51,   36,   54,    0,    0,    0,
        0,   47,   44,    0,   63,   49,   45,   50,   46,    0,
        0,   63,    0,   65,   48,    0,   60,   63,   63,    0,
       62,   43,   40,   38,   41,   42,   58,   55,   58,   58,

       58,   58,   58,   58,   26,   58,   58,   58,   58,   58,
       58,   22,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   56,   35,    0,    0,    0,   64,   37,
        0,    0,   65,   61,   53,   52,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   25,   58,   11,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    0,    0,    0,   64,   37,
        0,   70,    0,   65,   61,   53,   52,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   25,   58,
       11,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,    0,    0,   66,    3,
       58,   20,    9,   58,   58,   58,   58,   24,   19,   58,
       58,   28,   12,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,    8,   58,   58,    0,    0,   66,
        3,   58,   20,    9,   58,   58,   58,   58,   24,   19,
       58,   58,   28,   12,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,    8,   58,   58,    0,    0,
       30,   17,   58,   58,   58,   58,   13,   58,   58,   10,
       58,   58,   58,   58,   58,   58,   32,   58,   58,   27,
        0,    0,   30,   17,   58,   58,   58,   58,   13,   58,

       58,   10,   58,   58,   58,   58,   58,   58,   32,   58,
       58,   27,    0,    0,   58,   58,   14,    6,   58,   33,
       15,   34,    5,   31,   23,   58,   58,   58,    0,    0,
       58,   58,   14,    6,   58,   33,   15,   34,    5,   31,
       23,   58,   58,   58,    2,    0,   58,   21,   58,    7,
       58,   58,    2,    0,   58,   21,   58,    7,   58,   58,
        0,    0,    0,    2,    2,    0,    2,    2,    2,    2,
        0,    2,    2,    0,   29,    4,   16,   18,    0,   70,
        0,    0,    2,    2,    0,    2,    2,    2,    2,    0,
        2,    2,    0,   29,    4,   16,   18,    0,    0,    2,

        0,    0,    0,    0,    0,    0,    2,    0,    2,    2,
        2,    0,    2,    0,    0,    0,   70,    2,    0,    0,
        0,    0,    0,    0,    2,    0,    2,    2,    2,    0,
        2,    0,   70,    0,    0,    0,    0,    0,    0,   70,
        0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
        0,   70,    1,    0,    0,    0,    1,    0,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   30,   30,   32,   31,
       33,   34,   34,   33,   33,   35,   34,   34,   34,   34,
       33,   33,   34,   34,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   34,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   70,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   71,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    2,    3,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[578] =
    {   0,
        0,    0,   71,    0, 1512, 1513, 1509, 1507, 1504, 1481,
      136,   99, 1480,  134,  171, 1513, 1479,  131,  128,  141,
      151,  222,  228,  141, 1478,  142,    0, 1477, 1443, 1445,
      206,  102,  228,  157, 1446,  118, 1445, 1453,  203, 1434,
     1443, 1441, 1446,  229, 1491,  190, 1490,  261,  156,  260,
      255,  254,  265,  305, 1489,  266,  267,  374,  375,  384,
      387,  409,  271,  268,  274,  450,  276, 1431, 1433,  340,
      229,  362,  329, 1434,  332, 1433, 1441,  377, 1422, 1431,
     1429, 1434,  519, 1480, 1478, 1475, 1513,  265, 1513, 1476,
     1432, 1423, 1513, 1513, 1513,  388, 1464, 1463, 1404, 1513,

     1513,  412,  504, 1513, 1513, 1513, 1513, 1454,  507, 1513,
     1457,    0, 1513,  510,  522,  528, 1513,    0,  534, 1444,
     1513, 1513, 1513, 1443,    0, 1513, 1410, 1422, 1409, 1424,
     1411, 1417, 1403, 1404, 1401, 1401, 1404, 1401, 1398,    0,
     1397, 1401,  152, 1399,  340,  361, 1403, 1396,  333,  363,
     1401, 1513, 1513, 1447, 1513,  418,  435, 1446,  531,  378,
     1445, 1444,  148,  521, 1443, 1442, 1441,  556,  275,  434,
      532, 1440, 1439,  555,  560, 1438, 1437, 1436, 1435,  426,
      568, 1434,  537, 1433, 1432,  582,  590,  596, 1431,  626,
      604,  420, 1430, 1429, 1428,  545,    0, 1427, 1370, 1382,

     1369, 1384, 1371, 1377, 1363, 1364, 1361, 1361, 1364, 1361,
     1358,    0, 1357, 1361,  514, 1359,  519,  523, 1363, 1356,
      538,  545, 1361, 1407, 1406, 1361, 1363,  437, 1513, 1513,
     1391,  428,    0,    0, 1513, 1513, 1350, 1362, 1357, 1345,
      562, 1359, 1357, 1353, 1345, 1351, 1354,    0, 1340,    0,
     1346, 1343, 1332, 1334, 1336, 1343, 1329, 1327, 1327, 1339,
     1329, 1333, 1337, 1339, 1328,  561,  566,  627, 1376, 1375,
      591, 1362,  630, 1373,  671, 1372, 1371, 1318, 1330, 1325,
     1313,  576, 1327, 1325, 1321, 1313, 1319, 1322,    0, 1308,
        0, 1314, 1311, 1300, 1302, 1304, 1311, 1297, 1295, 1295,

     1307, 1297, 1301, 1305, 1307, 1296, 1297, 1294, 1513,    0,
     1294,    0,    0, 1285, 1293, 1282, 1289,    0,    0, 1283,
     1280,    0,    0, 1280, 1280, 1277, 1289, 1279, 1283, 1288,
     1287, 1285, 1275, 1280,    0, 1268, 1280,  613,  628, 1322,
        0, 1273,    0,    0, 1264, 1272, 1261, 1268,    0,    0,
     1262, 1259,    0,    0, 1259, 1259, 1256, 1268, 1258, 1262,
     1267, 1266, 1264, 1254, 1259,    0, 1247, 1259, 1250, 1243,
        0,    0, 1248, 1249, 1254, 1230,    0, 1200, 1185,    0,
     1158, 1155, 1157, 1141, 1150, 1151,    0, 1142, 1145,    0,
      598,  595,    0,    0, 1137, 1137, 1141, 1132,    0, 1123,

     1127,    0, 1135, 1132, 1134, 1115, 1124, 1126,    0, 1117,
     1120,    0, 1123, 1122, 1106, 1087,    0,    0, 1091,    0,
        0,    0,    0,    0,    0, 1089, 1088, 1077,  621,  634,
     1068, 1068,    0,    0, 1072,    0,    0,    0,    0,    0,
        0, 1068, 1054, 1047,  717, 1052, 1031,    0, 1012,    0,
     1019, 1009,  776,  635,  827,    0,  815,    0,  810,  808,
      638,  637,  832,  643, 1513,  663,  668,  722, 1513, 1513,
      835,  796,  792,  694,    0,    0,    0,    0,  903,  704,
      720,  974,  727,  810,  734,  739,  782,  807,  793,  643,
      674,  648,  804,    0,    0,    0,    0,  813,  725, 1513,

      784,  648,  758,  756,  681,  768, 1513,  798, 1027,  812,
     1513,    0, 1513, 1049,  821, 1054,  822,  725,  709,  762,
      722,  770,  656, 1044,  708, 1057, 1065, 1087,  685, 1117,
      675, 1100, 1109, 1069,  670,  618,  832,    0, 1119, 1128,
      781, 1162, 1055,  571, 1060,  863, 1513,  534,  394, 1122,
     1149, 1078,  270,  207,  744, 1132,  146, 1154, 1067, 1513,
     1209, 1212, 1218, 1224, 1230, 1236, 1239, 1244, 1250, 1255,
     1261, 1267, 1270, 1275, 1281, 1287, 1293
    } ;

static const flex_int16_t yy_def[578] =
    {   0,
      560,    1,  560,    3,  560,  560,  560,  560,  560,  560,
      561,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  562,  560,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  560,  563,  563,  560,  563,  563,  564,
      563,  563,  563,  560,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  560,  563,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,  563,  560,  560,  560,  560,  561,  560,  561,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,

      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      565,  566,  560,  560,  560,  560,  560,  567,  560,  560,
      560,  560,  560,  560,  562,  560,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  560,  560,  563,  560,  563,  563,  563,  564,  561,
      563,  564,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  568,  569,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,   66,  563,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,  563,  563,  560,  560,  560,  560,  560,
      565,  565,  566,  567,  560,  560,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  563,  563,  563,  563,  563,
      568,  565,  568,  569,  563,  563,  563,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,  560,  560,  560,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  563,  563,  563,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,  560,  560,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      563,  563,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,  560,  560,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  563,  563,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,  560,  560,  562,  562,  562,  562,
      562,  562,  563,  563,   66,   66,   66,   66,   66,   66,
      570,  571,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  562,  562,  562,  562,  560,  570,
      572,  560,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,   66,   66,   66,   66,  570,  571,  560,

      571,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  573,  560,  560,  479,  572,  571,  563,  572,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  560,  560,  560,  573,  574,  575,  563,  560,
      563,  563,  576,  577,  560,  574,  560,  574,  575,  563,
      576,  574,  563,  576,  577,  560,  575,  563,  577,    0,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560
    } ;

static const flex_int16_t yy_nxt[1585] =
    {   0,
        6,    7,    8,    6,    9,   10,   11,   12,    6,   13,
       14,   15,   16,   16,   17,   18,   16,   19,   20,   21,
       22,   23,   23,   16,   16,   24,   25,   26,   16,   27,
       27,   27,   27,   27,   27,   27,   27,   16,    6,   16,
       28,   29,   30,   31,   32,   33,   34,   35,   27,   36,
       27,   37,   27,   27,   27,   27,   38,   39,   40,   41,
       42,   43,   27,   27,   27,   16,   44,   16,   16,    6,
        6,   45,   46,   47,   45,   48,   49,   50,   51,   45,
       52,   53,   54,   55,   55,   56,   57,   55,   58,   59,
       60,   61,   62,   62,   55,   55,   63,   64,   65,   55,

       66,   66,   66,   66,   66,   66,   66,   66,   55,   45,
       55,   67,   68,   69,   70,   71,   72,   73,   74,   66,
       75,   66,   76,   66,   66,   66,   66,   77,   78,   79,
       80,   81,   82,   66,   66,   66,   55,   83,   55,   55,
       45,   45,   89,   91,   94,  105,  101,  132,   92,  102,
      155,  103,  103,  103,  106,  107,  133,  104,  155,  108,
       95,  109,  109,  109,  140,  111,  120,  121,  123,  124,
      112,  141,  110,  557,   90,   96,   97,  113,   97,   97,
       97,   97,  158,   97,   97,   97,   97,   97,   97,   97,
       97,  156,  155,  266,   97,   97,   97,   97,   97,  252,

       98,   97,   98,   97,   98,   98,   98,   98,  137,  155,
      253,  138,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   98,   97,   98,   97,
      114,   99,  115,  115,  116,  117,  114,  129,  119,  119,
      119,  144,  145,  117,  130,  152,  155,  155,  118,  117,
      131,  146,  160,  155,  147,  157,  161,  155,  155,  155,
      155,   89,  155,  155,  204,  166,  155,  155,  155,  134,
      165,  135,  173,  205,  118,  174,  269,  175,  175,  175,
      136,  167,  172,  176,  194,  153,  192,  193,  162,  163,

      195,  196,  198,   90,  164,  154,  154,  155,  154,  168,
      169,  154,  169,  169,  169,  169,  154,  169,  169,  169,
      169,  169,  169,  169,  169,  154,  154,  154,  169,  169,
      169,  169,  169,  154,  170,  169,  170,  169,  170,  170,
      170,  170,  154,  154,  154,  154,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      170,  169,  170,  169,  154,  171,  155,  155,  212,  189,
      209,  201,  261,  210,   89,  213,  155,  255,  202,  155,
      262,  177,  228,  180,  203,  181,  181,  181,  183,  229,

      178,  179,  257,  184,  256,  186,  182,  187,  187,  188,
      185,  155,  263,  206,  264,  207,   90,  258,  189,  156,
      155,  557,  155,  190,  208,  216,  217,  186,  155,  191,
      191,  191,  109,  109,  109,  218,  155,  155,  219,  157,
      189,  228,  232,  110,  270,  269,  276,  309,  229,  190,
      154,  154,  155,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      197,  197,  197,  154,  154,  154,  154,  154,  154,  197,
      197,  197,  197,  197,  197,  197,  197,  154,  154,  154,
      154,  197,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  154,  154,  154,  154,  154,
      154,  155,  114,  155,  116,  116,  116,  109,  109,  109,
      109,  109,  109,  160,  155,  117,  560,  161,  110,  272,
      114,  117,  115,  115,  116,  224,  114,  155,  116,  116,
      116,  273,  114,  117,  119,  119,  119,  155,  155,  117,
      268,  293,  155,  155,  298,  117,  296,  269,  155,  162,
      155,  277,  294,  155,  267,  181,  181,  181,  186,  299,
      188,  188,  188,  297,  155,  225,  182,  302,  181,  181,
      181,  189,  155,  272,  304,  303,  305,  155,  155,  182,

      155,  169,  181,  181,  181,  273,  155,  338,  186,  339,
      187,  187,  188,  189,  186,  155,  188,  188,  188,  314,
      315,  189,  186,  155,  191,  191,  191,  189,  155,  155,
      155,  268,  272,  345,  346,  189,  155,  155,  269,  461,
      461,  461,  461,  500,  273,  155,  275,  275,  275,  340,
      155,  429,  535,  500,  430,  275,  275,  275,  155,  500,
      484,  466,  391,  468,  468,  468,  453,  275,  275,  275,
      275,  275,  275,  155,  535,  501,  155,  155,  454,  392,
      493,  500,  489,  506,  506,  506,  508,  155,  509,  509,
      510,  275,  275,  275,  507,  514,  514,  514,  514,  511,

      275,  275,  275,  500,  512,  461,  461,  461,  461,  531,
      155,  155,  275,  275,  275,  275,  275,  275,  461,  461,
      461,  461,  517,  462,  155,  521,  518,  155,  463,  155,
      512,  500,  464,  518,  465,  466,  155,  467,  468,  468,
      508,  155,  510,  510,  510,  485,  155,  487,  487,  487,
      503,  469,  470,  511,  524,  524,  524,  526,  519,  527,
      527,  528,  471,  501,  155,  525,  541,  500,  472,  500,
      529,  559,  155,  518,  518,  530,  473,  479,  480,  479,
      479,  518,  481,  155,  155,  541,  560,  482,  506,  506,
      506,  483,  518,  484,  485,  155,  486,  487,  487,  507,

      526,  530,  528,  528,  528,  532,  533,  532,  532,  155,
      488,  489,  155,  529,  534,  534,  534,  534,  506,  506,
      506,  490,  539,  540,  539,  539,  470,  491,  500,  465,
      508,  513,  510,  510,  510,  492,  502,  503,  547,  503,
      503,  503,  503,  511,  503,  503,  503,  503,  503,  503,
      503,  503,  465,  497,  496,  503,  503,  503,  503,  503,
      501,  504,  503,  504,  503,  504,  504,  504,  504,  547,
      548,  495,  494,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  504,  503,  504,

      503,  548,  505,  154,  479,  480,  479,  479,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  515,  515,  515,  515,  515,  515,  515,  515,
      154,  154,  154,  154,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  154,  154,
      154,  154,  154,  154,  154,  154,  155,  154,  520,  521,
      154,  521,  521,  521,  521,  154,  521,  521,  521,  521,
      521,  521,  521,  521,  154,  154,  154,  521,  521,  521,

      521,  521,  154,  522,  521,  522,  521,  522,  522,  522,
      522,  154,  154,  154,  154,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  522,
      521,  522,  521,  154,  523,  508,  155,  509,  509,  510,
      514,  514,  514,  514,  478,  537,  517,  552,  511,  155,
      518,  553,  500,  477,  524,  524,  524,  155,  476,  155,
      534,  534,  534,  534,  538,  525,  475,  524,  524,  524,
      556,  556,  556,  526,  547,  527,  527,  528,  484,  155,
      545,  545,  519,  554,  559,  500,  529,  474,  460,  459,

      518,  532,  533,  532,  532,  526,  543,  528,  528,  528,
      514,  514,  514,  514,  458,  537,  548,  457,  529,  155,
      539,  540,  539,  539,  155,  544,  456,  455,  452,  534,
      534,  534,  534,  451,  538,  450,  449,  542,  542,  542,
      550,  550,  558,  558,  558,  448,  542,  542,  542,  545,
      545,  552,  556,  556,  556,  553,  155,  518,  542,  542,
      542,  542,  542,  542,  155,  447,  446,  500,  445,  444,
      443,  442,  441,  440,  558,  558,  558,  439,  438,  437,
      436,  435,  542,  542,  542,  434,  433,  554,  432,  518,
      431,  542,  542,  542,  428,  427,  426,  518,  425,  424,

      423,  422,  421,  542,  542,  542,  542,  542,  542,   88,
       88,   88,   88,   88,   88,  125,  125,  125,  154,  154,
      154,  154,  154,  154,  159,  159,  159,  159,  159,  159,
      231,  231,  231,  231,  231,  231,  233,  233,  420,  233,
      233,  233,  234,  234,  271,  271,  271,  271,  271,  271,
      274,  274,  274,  274,  274,  274,  498,  498,  419,  498,
      498,  499,  499,  499,  499,  499,  499,  516,  516,  516,
      516,  516,  516,  536,  536,  546,  546,  546,  546,  546,
      546,  549,  549,  418,  549,  549,  549,  551,  551,  551,
      551,  551,  551,  555,  555,  555,  555,  555,  555,  417,

      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  155,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  344,
      343,  342,  341,  155,  155,  155,  232,  155,  155,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,

      316,  313,  312,  311,  310,  232,  308,  307,  155,  155,
      306,  301,  300,  295,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      265,  260,  259,  254,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  232,  230,   97,  229,  229,  227,  226,  560,   86,
       85,   84,  223,  222,  221,  220,  215,  214,  211,  200,
      199,  155,   85,  155,  151,  150,  149,  148,  143,  142,

      139,  128,  127,  126,  122,  100,   93,   87,   86,   85,
       84,  560,    5,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560
    } ;

static const flex_int16_t yy_chk[1585] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   11,   12,   14,   19,   18,   32,   12,   18,
      163,   18,   18,   18,   19,   19,   32,   18,   49,   20,
       14,   20,   20,   20,   36,   21,   24,   24,   26,   26,
       21,   36,   20,  557,   11,   15,   15,   21,   15,   15,
       15,   15,   49,   15,   15,   15,   15,   15,   15,   15,
       15,   46,   46,  163,   15,   15,   15,   15,   15,  143,

       15,   15,   15,   15,   15,   15,   15,   15,   34,  554,
      143,   34,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       22,   15,   22,   22,   22,   33,   23,   31,   23,   23,
       23,   39,   39,   22,   31,   44,   52,   51,   22,   23,
       31,   39,   50,   48,   39,   48,   50,   53,   56,   57,
       64,   88,  553,   63,   71,   53,   65,  169,   67,   33,
       52,   33,   57,   71,   22,   57,  169,   57,   57,   57,
       33,   53,   56,   57,   64,   44,   63,   63,   50,   51,

       65,   65,   67,   88,   51,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   58,   59,   75,   72,
       73,   70,  149,   73,  160,   75,   60,  145,   70,   61,
      149,   58,   96,   59,   70,   59,   59,   59,   60,   96,

       58,   58,  146,   60,  145,   61,   59,   61,   61,   61,
       60,   62,  150,   72,  150,   72,  160,  146,   61,  156,
      156,  549,  192,   61,   72,   78,   78,   62,  180,   62,
       62,   62,  102,  102,  102,   78,  170,  157,   78,  157,
       62,  228,  232,  102,  180,  170,  192,  232,  228,   61,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   83,  103,  164,  103,  103,  103,  109,  109,  109,
      114,  114,  114,  159,  171,  103,  548,  159,  109,  183,
      115,  114,  115,  115,  115,   83,  116,  196,  116,  116,
      116,  183,  119,  115,  119,  119,  119,  174,  168,  116,
      168,  215,  175,  266,  218,  119,  217,  168,  267,  159,
      181,  196,  215,  544,  164,  174,  174,  174,  175,  218,
      175,  175,  175,  217,  186,   83,  174,  221,  181,  181,
      181,  175,  187,  271,  222,  221,  222,  392,  188,  181,

      391,  171,  186,  186,  186,  271,  191,  266,  187,  267,
      187,  187,  187,  186,  188,  338,  188,  188,  188,  241,
      241,  187,  191,  429,  191,  191,  191,  188,  190,  268,
      339,  268,  273,  282,  282,  191,  430,  454,  268,  461,
      461,  461,  461,  462,  273,  490,  190,  190,  190,  273,
      492,  391,  502,  536,  392,  190,  190,  190,  523,  502,
      490,  464,  338,  464,  464,  464,  429,  190,  190,  190,
      190,  190,  190,  275,  535,  462,  491,  531,  430,  339,
      454,  535,  492,  466,  466,  466,  467,  529,  467,  467,
      467,  275,  275,  275,  466,  474,  474,  474,  474,  467,

      275,  275,  275,  467,  467,  480,  480,  480,  480,  491,
      525,  519,  275,  275,  275,  275,  275,  275,  445,  445,
      445,  445,  481,  445,  521,  523,  481,  518,  445,  483,
      467,  499,  445,  521,  445,  445,  485,  445,  445,  445,
      468,  486,  468,  468,  468,  483,  555,  483,  483,  483,
      505,  445,  445,  468,  485,  485,  485,  486,  481,  486,
      486,  486,  445,  499,  520,  485,  520,  504,  445,  503,
      486,  555,  522,  520,  486,  486,  445,  453,  453,  453,
      453,  522,  453,  541,  487,  541,  501,  453,  506,  506,
      506,  453,  541,  453,  453,  489,  453,  453,  453,  506,

      487,  486,  487,  487,  487,  493,  493,  493,  493,  488,
      453,  453,  484,  487,  498,  498,  498,  498,  508,  508,
      508,  453,  515,  515,  515,  515,  473,  453,  517,  508,
      510,  472,  510,  510,  510,  453,  463,  463,  537,  463,
      463,  463,  463,  510,  463,  463,  463,  463,  463,  463,
      463,  463,  471,  460,  459,  463,  463,  463,  463,  463,
      517,  463,  463,  463,  463,  463,  463,  463,  463,  546,
      537,  457,  455,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  546,  463,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  509,  524,  509,  509,  509,
      514,  514,  514,  514,  452,  514,  516,  543,  509,  526,
      516,  543,  509,  451,  524,  524,  524,  527,  449,  559,
      534,  534,  534,  534,  514,  524,  447,  526,  526,  526,
      545,  545,  545,  527,  552,  527,  527,  527,  526,  528,
      534,  534,  516,  543,  559,  545,  527,  446,  444,  443,

      527,  532,  532,  532,  532,  528,  532,  528,  528,  528,
      533,  533,  533,  533,  442,  533,  552,  435,  528,  530,
      539,  539,  539,  539,  550,  532,  432,  431,  428,  540,
      540,  540,  540,  427,  533,  426,  419,  530,  530,  530,
      539,  539,  550,  550,  550,  416,  530,  530,  530,  540,
      540,  551,  556,  556,  556,  551,  558,  550,  530,  530,
      530,  530,  530,  530,  542,  415,  414,  556,  413,  411,
      410,  408,  407,  406,  558,  558,  558,  405,  404,  403,
      401,  400,  542,  542,  542,  398,  397,  551,  396,  558,
      395,  542,  542,  542,  389,  388,  386,  542,  385,  384,

      383,  382,  381,  542,  542,  542,  542,  542,  542,  561,
      561,  561,  561,  561,  561,  562,  562,  562,  563,  563,
      563,  563,  563,  563,  564,  564,  564,  564,  564,  564,
      565,  565,  565,  565,  565,  565,  566,  566,  379,  566,
      566,  566,  567,  567,  568,  568,  568,  568,  568,  568,
      569,  569,  569,  569,  569,  569,  570,  570,  378,  570,
      570,  571,  571,  571,  571,  571,  571,  572,  572,  572,
      572,  572,  572,  573,  573,  574,  574,  574,  574,  574,
      574,  575,  575,  376,  575,  575,  575,  576,  576,  576,
      576,  576,  576,  577,  577,  577,  577,  577,  577,  375,

      374,  373,  370,  369,  368,  367,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  352,  351,  348,
      347,  346,  345,  342,  340,  337,  336,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  321,  320,
      317,  316,  315,  314,  311,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  290,  288,  287,  286,  285,  284,  283,  281,
      280,  279,  278,  277,  276,  274,  272,  270,  269,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  249,  247,  246,  245,  244,  243,

      242,  240,  239,  238,  237,  231,  227,  226,  225,  224,
      223,  220,  219,  216,  214,  213,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      195,  194,  193,  189,  185,  184,  182,  179,  178,  177,
      176,  173,  172,  167,  166,  165,  162,  161,  158,  154,
      151,  148,  147,  144,  142,  141,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  124,
      120,  111,  108,   99,   98,   97,   92,   91,   90,   86,
       85,   84,   82,   81,   80,   79,   77,   76,   74,   69,
       68,   55,   47,   45,   43,   42,   41,   40,   38,   37,

       35,   30,   29,   28,   25,   17,   13,   10,    9,    8,
        7,    5,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[72] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[71] =
    {   0,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
      111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
      131,  132,  133,  134,  135,  136,  137,  138,  139,  140
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "flex.l"
#line 6 "flex.l"
#include <stdio.h>
#include <string.h>
#include "bison.tab.h"
#include "tp5.h"

int comentario = 0;

#line 1111 "lex.yy.c"
/* DEFINICIONES */
/******* DIRECTIVAS PREPROCESAMIENTO *******/
/**************** CONSTANTES ENTERAS *****************/
/******* Constantes Enteras Decimales *******/
/******** Constante Real *********/
/******** Constante Caracter ********/
/****************** LITERAL CADENA *******************/
/******************* IDENTIFICADOR *******************/
/********* Secuencia de Escape **********/
/********* Digitos y Caracteres  ********/
/****************** COMENTARIOS *********************/
/**** OTROS ****/

#line 1125 "lex.yy.c"

#define INITIAL 0
#define NO_RECONOCIDO 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 70 "flex.l"

#line 1408 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 561 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1513 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 71 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 71 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 72 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 71 "flex.l"
{return INCLUDE;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 72 "flex.l"
{return DEFINE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "flex.l"
{return AUTO;} 	
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "flex.l"
{return REGISTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "flex.l"
{return STATIC;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "flex.l"
{return EXTERN;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "flex.l"
{return TYPEDEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "flex.l"
{yylval.cval = yytext; return VOID;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "flex.l"
{yylval.cval = yytext; return CHAR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "flex.l"
{return SHORT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "flex.l"
{yylval.cval = yytext; return INT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "flex.l"
{return LONG;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "flex.l"
{yylval.cval = yytext; return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "flex.l"
{yylval.cval = yytext; return DOUBLE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "flex.l"
{return SIGNED;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "flex.l"
{return UNSIGNED;}	
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "flex.l"
{return CONST;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "flex.l"
{return VOLATILE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "flex.l"
{yylval.cval = yytext; return ENUM;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "flex.l"
{return CASE;}	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "flex.l"
{return DEFAULT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "flex.l"
{return IF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "flex.l"
{return SWITCH;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "flex.l"
{return ELSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "flex.l"
{return FOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "flex.l"
{return DO;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 97 "flex.l"
{return WHILE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 98 "flex.l"
{return GOTO;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "flex.l"
{return CONTINUE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "flex.l"
{return BREAK;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 101 "flex.l"
{yylval.cval = yytext; return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 102 "flex.l"
{yylval.cval = yytext; return UNION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 103 "flex.l"
{return RETURN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "flex.l"
{return SIZEOF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "flex.l"
{return CTE_OR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "flex.l"
{return CTE_AND;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "flex.l"
{return ELIPSIS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "flex.l"
{return IGUAL_IGUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "flex.l"
{return DISTINTO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "flex.l"
{return MENOR_IGUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "flex.l"
{return MAYOR_IGUAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 112 "flex.l"
{return CORR_DER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 113 "flex.l"
{return CORR_IZQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 114 "flex.l"
{return MAS_MAS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "flex.l"
{return MENOS_MENOS;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "flex.l"
{return FLECHA;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "flex.l"
{return POR_IGUAL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "flex.l"
{return DIV_IGUAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "flex.l"
{return MAS_IGUAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "flex.l"
{return MENOS_IGUAL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "flex.l"
{return MOD_IGUAL;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "flex.l"
{return CORR_DER_IGUAL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "flex.l"
{return CORR_IZQ_IGUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "flex.l"
{return Y_IGUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "flex.l"
{return POT_IGUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "flex.l"
{return O_IGUAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "flex.l"
{return yytext[0];}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "flex.l"
{if(comentario == 0) {yylval.cval = yytext; return IDENTIFICADOR;}}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 129 "flex.l"
{if(comentario == 0) return LITERAL_CADENA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 130 "flex.l"
{if(comentario == 0) return CONST_OCTAL;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "flex.l"
{if(comentario == 0) return CONST_HEXADECIMAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "flex.l"
{if(comentario == 0) return CONST_DECIMAL;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "flex.l"
{if(comentario == 0) return CONST_PTOFLOTANTE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "flex.l"
{if(comentario == 0) return CONST_CARACTER;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "flex.l"
{if(comentario == 0) comentario=1;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 136 "flex.l"
{if(comentario == 1) comentario = 0; else comentario = 1;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "flex.l"
{;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 138 "flex.l"
{comentario=0;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "flex.l"
{analisisCorrecto = 0; BEGIN(NO_RECONOCIDO);}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 140 "flex.l"
{printf("\nseg?\n"); strcat(NO_RECONOCIDO, yytext); BEGIN(INITIAL); yylval.idval = strdup(NO_RECONOCIDO); return NO_RECONOCIDO;printf("\nseg\n");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "flex.l"
ECHO;
	YY_BREAK
#line 1859 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NO_RECONOCIDO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 561 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 561 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 560);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 141 "flex.l"





