/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
static yyconst short int yy_acclist[268] =
    {   0,
       16,   14,   15,   13,   14,   15,   13,   15,   13,   14,
       15,    5,   14,   15,   14,   15,    5,   14,   15,    5,
       14,   15,    5,   14,   15,   14,   15,    5,   14,   15,
        5,   14,   15,    5,   14,   15,    5,   14,   15,    5,
        9,   14,   15,    5,   14,   15,    6,   14,   15,    8,
       14,   15,    5,   14,   15,    5,   14,   15,    5,   14,
       15,    4,   14,   15,    5,   14,   15,    4,   14,   15,
        4,   14,   15,    4,   14,   15,    4,   14,   15,    4,
       14,   15,    4,   14,   15,    4,   14,   15,    4,   14,
       15,    4,   14,   15,    4,   14,   15,    4,   14,   15,

        4,   14,   15,    4,   14,   15,    4,   14,   15,    4,
       14,   15,    5,   14,   15,   13,   13,   13,    5,    2,
        9,    9,   11,    9,    6,    8,    5,    5,    4,    4,
        4,    4,    4,    4,    4,    3,    4,    4,    4,    4,
        4,    4,    4,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,   10,    9,   11,    9,
        7,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
       11,   12,    9,    3,    4,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,   12,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
       11,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_accept[253] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       20,   23,   26,   28,   31,   34,   37,   40,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  117,  118,  119,  120,  120,  121,  121,
      121,  121,  121,  121,  121,  122,  122,  122,  123,  123,
      123,  124,  125,  126,  126,  126,  126,  127,  128,  129,
      130,  131,  132,  133,  134,  135,  136,  138,  139,  140,
      141,  142,  143,  144,  146,  147,  148,  149,  150,  151,
      152,  153,  154,  155,  156,  157,  157,  157,  158,  158,

      159,  159,  159,  159,  160,  160,  160,  161,  162,  163,
      164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
      174,  176,  177,  178,  179,  180,  181,  182,  183,  184,
      185,  186,  187,  188,  189,  190,  191,  191,  191,  191,
      193,  193,  194,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  216,  216,  217,  217,  217,  218,
      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  230,  231,  231,  231,  232,  233,  234,  235,  236,
      237,  238,  238,  238,  239,  240,  241,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  243,  244,
      245,  245,  246,  246,  246,  246,  247,  247,  247,  247,
      247,  247,  248,  248,  249,  250,  250,  250,  251,  252,
      252,  253,  254,  255,  256,  256,  257,  257,  257,  258,
      259,  260,  261,  262,  263,  263,  264,  265,  266,  267,
      268,  268
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   29,   29,   31,   30,
       32,   33,   33,   32,   32,   34,   33,   33,   33,   33,
       32,   32,   33,   33,   35,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   33,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   32,   50,   51,   52,   53,
       54,   55,   32,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    2,    3,    2,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    7,    7,    7,    7,    7,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    8,    1,    8,    1
    } ;

static yyconst short int yy_base[266] =
    {   0,
        0,    0,  630,  631,  627,  625,  622,  600,   62,   62,
      599,   61,   68,  631,  598,   57,   64,   74,   94,   94,
      106,   63,  597,   83,    0,  596,  562,  564,   81,   53,
       70,   80,  565,   87,  564,  572,   94,  553,  562,  560,
      565,   91,  610,  608,  605,  631,  111,  631,  606,  563,
      554,   69,  595,  594,  138,  143,  586,  146,  158,  133,
        0,  150,  172,  178,  190,    0,  198,  577,  576,    0,
      543,  555,  542,  557,  544,  550,  536,  537,  534,  534,
      537,  534,  531,    0,  530,  534,  129,  532,   29,   97,
      536,  529,   97,   99,  534,  536,  538,  631,  164,  193,

      194,  566,  218,    0,  213,  204,  218,    0,  525,  537,
      532,  520,   87,  534,  532,  528,  520,  526,  529,  515,
        0,  521,  518,  507,  509,  511,  518,  504,  502,  502,
      514,  504,  508,  512,  514,  503,  504,  501,  187,  537,
      224,  227,    0,  500,  491,  499,  488,  495,  489,  486,
      481,  467,  452,  456,  429,  417,  412,  404,  402,  388,
      390,  378,  389,  377,  370,  631,  413,  208,  373,  370,
      375,  363,  354,  350,  351,  325,  322,  306,  312,  309,
      300,  292,  291,  290,  316,  269,  256,  257,  248,  243,
      235,  248,  239,  237,  219,  192,  186,  252,  256,  260,

      264,  288,  234,    0,  235,  282,  256,  276,  304,  311,
      263,  631,  201,  175,  274,  631,  186,  274,  171,  151,
      330,  337,  352,  356,  363,  368,  385,  245,  249,    0,
      397,  284,  286,  114,  371,  389,  418,  403,  423,  631,
      631,  345,  631,  631,  429,  432,  288,  293,  631,  631,
      631,  456,  461,  465,  472,  480,  484,  490,  498,  505,
      512,  520,  528,  533,  537
    } ;

static yyconst short int yy_def[266] =
    {   0,
      251,    1,  251,  251,  251,  251,  251,  251,  252,  251,
      251,  251,  253,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  254,  251,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  251,  251,  251,  251,  251,  252,  251,  252,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  255,
      256,  251,  251,  251,  251,  257,  251,  251,  251,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  251,  251,  251,  251,  251,

      255,  258,  255,  256,  251,  251,  251,  257,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  251,  251,  258,  259,
      251,  251,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  251,  251,  251,  259,  259,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  251,  251,  259,  254,  254,  254,  254,  254,
      254,  251,  251,  254,  254,  254,  254,  260,  251,  260,

      251,  251,  261,  262,  263,  264,  251,  251,  251,  251,
      261,  251,  261,  262,  263,  251,  263,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  265,
      251,  251,  251,  262,  251,  251,  251,  251,  251,  251,
      251,  265,  251,  251,  251,  251,  251,  251,  251,  251,
        0,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251
    } ;

static yyconst short int yy_nxt[700] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   14,   15,   16,   14,   17,   18,   19,   20,
       21,   21,   14,   14,   22,   23,   24,   14,   25,   25,
       25,   25,   25,   25,   25,   25,   14,    4,   14,   26,
       27,   28,   29,   30,   31,   32,   33,   25,   34,   25,
       35,   25,   25,   25,   25,   36,   37,   38,   39,   40,
       41,   25,   25,   25,   14,   42,   14,   14,   48,   46,
       46,   46,   52,   52,   55,  126,   56,   56,   56,   98,
       46,   55,   46,   56,   56,   56,   46,   68,   46,   46,
       46,   57,  127,   58,   58,   58,   53,   76,   53,   49,

       53,   53,   53,   53,   59,   50,   77,   60,   46,   69,
       51,   62,   61,   63,   63,   64,   46,   48,   59,   46,
       78,   73,   79,   62,   65,   67,   67,   67,   74,   66,
       81,   80,   84,   82,   75,  102,   65,  128,   65,   85,
      234,   88,   89,  145,  146,  132,  103,  134,   49,  135,
       65,   90,  129,  133,   91,   66,   46,   58,   58,   58,
       62,  216,   64,   64,   64,   58,   58,   58,   59,   58,
       58,   58,   99,   65,   99,  123,   59,  100,  100,  100,
      105,  216,   59,  100,  100,  100,  124,   65,  251,   62,
       59,   63,   63,   64,  105,   62,  102,   64,   64,   64,

      139,  234,   65,  251,  106,  166,  106,  103,   65,  107,
      107,  107,  100,  100,  100,   62,   65,   67,   67,   67,
      102,  168,   65,  107,  107,  107,  185,  141,   65,  141,
      143,  103,  142,  142,  142,  121,  140,  107,  107,  107,
      212,  216,   65,  142,  142,  142,  142,  142,  142,  198,
      198,  198,  198,  198,  198,  198,  198,  201,  201,  201,
      201,  202,  202,  202,  202,  201,  201,  201,  201,  212,
      203,  213,  217,  208,  143,  221,  221,  221,  218,  240,
      216,   84,  241,  199,  216,  197,  218,  196,  204,  202,
      202,  202,  202,  143,  205,  222,  222,  222,  206,  241,

      213,  195,  207,  240,  207,  208,  223,  209,  210,  210,
      219,  217,  219,  143,  219,  219,  219,  219,  243,  244,
      223,  224,  249,  225,  225,  226,  250,  194,  224,  168,
      231,  231,  231,  193,  227,  192,  244,  228,  229,  230,
      191,  227,  243,  250,  232,  233,  249,  224,  227,  226,
      226,  226,  190,  189,  228,  227,  222,  222,  222,   84,
      227,  232,  229,  143,  143,  230,  235,  223,  235,  233,
      143,  236,  236,  236,  227,  222,  222,  222,  247,  248,
      224,  223,  225,  225,  226,  224,  237,  226,  226,  226,
      236,  236,  236,  227,  121,  247,  228,  229,  227,  238,

      237,  238,  143,  248,  239,  239,  239,  227,  236,  236,
      236,  188,  227,  228,  224,  143,  231,  231,  231,  121,
      187,  229,  239,  239,  239,  186,  168,  227,  184,  183,
      232,  233,  245,   84,  245,  182,  181,  246,  246,  246,
      143,  227,  239,  239,  239,  180,  179,  232,  246,  246,
      246,  246,  246,  246,  178,  233,   47,   47,   47,   47,
       47,   47,   47,   47,   54,  177,   54,   54,   54,   70,
       70,   70,  101,  101,  101,  101,  101,  101,  101,  101,
      104,  104,  176,  104,  104,  104,  104,  104,  108,  108,
      102,  102,  102,  102,  102,  102,  102,  102,  167,  167,

      175,  167,  167,  167,  167,  167,  200,  200,  200,  121,
      200,  200,  211,  211,  211,  211,  211,  211,  211,  211,
      214,  214,  174,  214,  214,  214,  214,  214,  215,  215,
      215,  215,  215,  215,  215,  215,  220,  173,  220,  220,
      220,  242,  242,  121,  172,  171,  170,  169,  143,   84,
      168,  165,  164,  163,  162,  121,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  121,  143,  150,
      149,  143,  143,  148,  147,  121,  143,  144,  143,  139,
      138,  137,  136,  131,  130,  125,  122,  121,  120,   84,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  110,

      109,   46,   46,   46,   98,   98,   97,   96,  251,   45,
       44,   43,   95,   94,   93,   92,   87,   86,   83,   72,
       71,   46,   46,   46,   46,   46,   45,   44,   43,  251,
        3,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251

    } ;

static yyconst short int yy_chk[700] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       12,   16,   13,   52,   16,   89,   16,   16,   16,   52,
       17,   17,   16,   17,   17,   17,   12,   22,   22,   17,
       17,   18,   89,   18,   18,   18,   13,   30,   13,    9,

       13,   13,   13,   13,   18,   10,   30,   19,   24,   24,
       10,   20,   19,   20,   20,   20,   42,   47,   18,   19,
       31,   29,   31,   21,   20,   21,   21,   21,   29,   20,
       32,   31,   34,   32,   29,   60,   21,   90,   20,   34,
      234,   37,   37,  113,  113,   93,   60,   94,   47,   94,
       21,   37,   90,   93,   37,   20,   42,   55,   55,   55,
       56,  220,   56,   56,   56,   58,   58,   58,   55,   62,
       62,   62,   59,   56,   59,   87,   58,   59,   59,   59,
       62,  219,   55,   99,   99,   99,   87,   56,  217,   63,
       58,   63,   63,   63,   62,   64,  101,   64,   64,   64,

      139,  214,   63,  213,   65,  139,   65,  101,   64,   65,
       65,   65,  100,  100,  100,   67,   63,   67,   67,   67,
      103,  168,   64,  106,  106,  106,  168,  105,   67,  105,
      197,  103,  105,  105,  105,  196,  103,  107,  107,  107,
      203,  205,   67,  141,  141,  141,  142,  142,  142,  192,
      192,  192,  192,  198,  198,  198,  198,  199,  199,  199,
      199,  200,  200,  200,  200,  201,  201,  201,  201,  211,
      201,  203,  205,  207,  195,  207,  207,  207,  218,  228,
      215,  194,  229,  193,  218,  191,  206,  190,  201,  202,
      202,  202,  202,  189,  202,  208,  208,  208,  202,  229,

      211,  188,  202,  228,  202,  202,  208,  202,  202,  202,
      206,  215,  206,  187,  206,  206,  206,  206,  232,  233,
      208,  209,  247,  209,  209,  209,  248,  186,  210,  185,
      210,  210,  210,  184,  209,  183,  233,  209,  209,  209,
      182,  210,  232,  248,  210,  210,  247,  221,  209,  221,
      221,  221,  181,  180,  209,  210,  222,  222,  222,  179,
      221,  210,  209,  178,  177,  209,  223,  222,  223,  210,
      176,  223,  223,  223,  221,  224,  224,  224,  242,  242,
      225,  222,  225,  225,  225,  226,  224,  226,  226,  226,
      235,  235,  235,  225,  175,  242,  225,  225,  226,  227,

      224,  227,  174,  242,  227,  227,  227,  225,  236,  236,
      236,  173,  226,  225,  231,  172,  231,  231,  231,  171,
      170,  225,  238,  238,  238,  169,  167,  231,  165,  164,
      231,  231,  237,  163,  237,  162,  161,  237,  237,  237,
      160,  231,  239,  239,  239,  159,  158,  231,  245,  245,
      245,  246,  246,  246,  157,  231,  252,  252,  252,  252,
      252,  252,  252,  252,  253,  156,  253,  253,  253,  254,
      254,  254,  255,  255,  255,  255,  255,  255,  255,  255,
      256,  256,  155,  256,  256,  256,  256,  256,  257,  257,
      258,  258,  258,  258,  258,  258,  258,  258,  259,  259,

      154,  259,  259,  259,  259,  259,  260,  260,  260,  153,
      260,  260,  261,  261,  261,  261,  261,  261,  261,  261,
      262,  262,  152,  262,  262,  262,  262,  262,  263,  263,
      263,  263,  263,  263,  263,  263,  264,  151,  264,  264,
      264,  265,  265,  150,  149,  148,  147,  146,  145,  144,
      140,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  120,  119,
      118,  117,  116,  115,  114,  112,  111,  110,  109,  102,
       97,   96,   95,   92,   91,   88,   86,   85,   83,   82,
       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,

       71,   69,   68,   57,   54,   53,   51,   50,   49,   45,
       44,   43,   41,   40,   39,   38,   36,   35,   33,   28,
       27,   26,   23,   15,   11,    8,    7,    6,    5,    3,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "categorias-lexicas.l"
#define INITIAL 0
/* %option debug */
#line 6 "categorias-lexicas.l"
#include "categorias-lexicas.h"

ListaIdentificadores* identificadores;
ListaStrings* cadenas;
ListaStrings* palabrasReservadas;
ListaStrings* operadoresCtesPuntuacion;
int operadoresCtesPuntuacionEncontrados;

ListaInt* octales;
ListaInt* hexadecimales;
ListaInt* decimales;
int acumuladorDecimal;

ListaDouble* reales;
char caracteres[100];

int caracteresEncontrados;

ListaStrings *comentarios;
ListaStrings *directivas;
ListaStrings *noReconocidos;

/* DEFINICIONES */
/******* DIRECTIVAS PREPROCESAMIENTO *******/
/**************** PALABRAS RESERVADAS ****************/
/******* OPERADORES Y CARACTERES DE PUNTUACION *******/
/**************** CONSTANTES ENTERAS *****************/
/******* Constantes Enteras Decimales *******/
/******** Constante Real *********/
/******** Constante Caracter ********/
/****************** LITERAL CADENA *******************/
/******************* IDENTIFICADOR *******************/
/********* Secuencia de Escape **********/
/********* Digitos y Caracteres  ********/
/****************** COMENTARIOS *********************/
/**** OTROS ****/
#line 685 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 90 "categorias-lexicas.l"

#line 838 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 252 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 631 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 91 "categorias-lexicas.l"
{agregarString(directivas, yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 92 "categorias-lexicas.l"
{agregarStringAuxFuncion(cadenas, yytext, strlenMenosDos);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 93 "categorias-lexicas.l"
{agregarString(palabrasReservadas, yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 94 "categorias-lexicas.l"
{agregarIdentificador(identificadores, yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 95 "categorias-lexicas.l"
{if(!stringIncrementarSiRegistrado(operadoresCtesPuntuacion, operadoresCtesPuntuacionEncontrados, yytext)){agregarStringAux(operadoresCtesPuntuacion, yytext, 1); operadoresCtesPuntuacionEncontrados++;} }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 96 "categorias-lexicas.l"
{agregarInt(octales, atoi(yytext));}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "categorias-lexicas.l"
{agregarInt(hexadecimales, strtol(yytext, NULL, 16));}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 98 "categorias-lexicas.l"
{agregarInt(decimales, atoi(yytext)); acumuladorDecimal += atoi(yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "categorias-lexicas.l"
{agregarDouble(reales, strtod(yytext, NULL));}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "categorias-lexicas.l"
{if(!caracterYaEstaRegistrado(caracteres, caracteresEncontrados, yytext[1])){caracteres[caracteresEncontrados] = yytext[1];caracteresEncontrados++;}}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "categorias-lexicas.l"
{agregarStringAux(comentarios, yytext, 0);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "categorias-lexicas.l"
{agregarStringAux(comentarios, yytext, 1);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "categorias-lexicas.l"
{;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "categorias-lexicas.l"
{agregarStringAux(noReconocidos, yytext, yylineno); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 105 "categorias-lexicas.l"
ECHO;
	YY_BREAK
#line 1004 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 252 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 252 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 251);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 105 "categorias-lexicas.l"

int main()
{
    printf("[LOG]: Inicio del programa (1/5)\n");
    yyin = fopen("input.c", "r+");
    FILE* reporte = fopen("reporte.txt", "w+");

    printf("[LOG]: Inicializando variables (2/5)\n");

    //Inicializacion
    identificadores = inicializarListaIdentificadores(identificadores);
    cadenas = inicializarListaStrings(cadenas);
    palabrasReservadas = inicializarListaStrings(palabrasReservadas);
    octales = inicializarListaInt(octales);
    hexadecimales = inicializarListaInt(hexadecimales);
    decimales = inicializarListaInt(decimales);
    acumuladorDecimal = 0;
    reales = inicializarListaDouble(reales);
    caracteresEncontrados = 0;
    operadoresCtesPuntuacion = inicializarListaStrings(operadoresCtesPuntuacion);
    operadoresCtesPuntuacionEncontrados = 0;
    comentarios = inicializarListaStrings(comentarios);
    directivas = inicializarListaStrings(directivas);
    noReconocidos = inicializarListaStrings(noReconocidos);

    printf("[LOG]: Corriendo analizador lexico (3/5)\n");
    yylex();

    printf("[LOG]: Generando reporte (4/5)\n");
    crearListadoIdentificadores(reporte, identificadores);
    crearListadoLiteralesCadena(reporte, cadenas);
    crearListadoPalabrasReservadas(reporte, palabrasReservadas);
    crearListadoCtesInt(reporte, octales, 8, NULL);
    crearListadoCtesInt(reporte, hexadecimales, 16, NULL);
    crearListadoCtesInt(reporte, decimales, 10, &acumuladorDecimal);
    crearListadoCtesReales(reporte, reales);
    crearListadoCtesCaracter(reporte, caracteres, caracteresEncontrados);
    crearListadoOperadoresCtesPuntuacion(reporte, operadoresCtesPuntuacion);
    crearListadoComentarios(reporte, comentarios);
    crearListadoNoReconocidos(reporte, noReconocidos);
    crearListadoDirectivas(reporte, directivas);

    fclose(yyin);
    fclose(reporte);

    printf("[LOG]: Fin del programa (5/5)\n");

    return 0;
}